### ISSUE TITLE
 Unable to find the targets named

### ISSUE THREAD

**Issue by fozoglu** [agilie/AGLocationDispatcher#1]
I want to review demo app.  I'm clone the repo and getting an exception when running pod install:

[!] Unable to find the targets named `AGGeoTrackingDemo`to link with target definition `AGGeoTrackingDemo

How do I fix the error?

Thanks.

**Comment by kalamaznik** [comment]
Our fix refer to Pod target names

**Comment by fozoglu** [comment]
Thank you. Examples working.
