### ISSUE TITLE
Can`t install AGLocationDispatcher

### ISSUE THREAD

**Issue by gtarashuk** [agilie/AGLocationDispatcher#3]
First of all let me thank you for this awesome work!

I want to use it but I can`t do it :(

I`m doing pod update with AGLocationDispatcher pod inside podfile and getting this error:
[!] Error installing FileMD5Hash
[!] /usr/bin/git checkout --quiet d00c0c51c6d0955d9daf94c30cfd95a219d4914e

fatal: reference is not a tree: d00c0c51c6d0955d9daf94c30cfd95a219d4914e

Please help me!

Thanks!

**Comment by gtarashuk** [comment]
Another problem is for RestKit I need Afnetworking 1.3.4 and for AGLocationDispatcher I need AFNetworking 2.6.3

**Comment by kalamaznik** [comment]
Hello gtarashuk.

According to your pod update issue: try to delete Podflie.lock in project folder and perform "pod install" freshly.

As for AFNetworking: version 1.3 is not supported. If you want to use v. 1.3 make pull request and tune this library according to your requirements.

**Comment by gtarashuk** [comment]
Thank you!
