### ISSUE TITLE
time interval

### ISSUE THREAD

**Issue by mythodeia** [agilie/AGLocationDispatcher#4]
the comments for `startUpdatingLocationWithBlock` state:
 `get current position every time interval` 
however this method does not use the time interval i setup in:  

```
self.demoLocationDispatcher = [[AGLocationDispatcher alloc] initWithUpdatingInterval:kAGLocationUpdateIntervalOneMinute andDesiredAccuracy:kAGHorizontalAccuracyHouse]; 
```

the scenario i am trying to cover is this:
while the app is in the foreground do a location update every x time (minutes).
while the app is in the background use the `AGBackgroundLocationDispatcher` to get location updates.
so i used the code from the `AGGeoBackgroundDemo` demo and i only changed the code in the ViewController.m to use `startUpdatingLocationWithBlock` instead of `currentLocationWithBlock`.

is there a way to make startUpdatingLocationWithBlock work with the time interval i want?

thanks for the library and of course your time :+1:

**Comment by kalamaznik** [comment]
Hello. Let's clarify you issue.
You try to use dispatcher:
[[AGLocationDispatcher alloc] initWithUpdatingInterval:kAGLocationUpdateIntervalOneMinute andDesiredAccuracy:kAGHorizontalAccuracyHouse] in foreground?
And startUpdatingLocationWithBlock method doesn't use your time interval in foreground or in background?

Thanks for your question.

**Comment by mythodeia** [comment]
sorry if i was not clear enough. Let me try to explain my issue better.

in the AGLocationDispatcher.h file the comments for startUpdatingLocationWithBlock state: 
`get current position every time interval` so i tried this:

```
        self.demoLocationDispatcher = [[AGLocationDispatcher alloc] initWithUpdatingInterval:kAGLocationUpdateIntervalTenSec
                                                                          andDesiredAccuracy:kAGHorizontalAccuracyHouse];

        [self.demoLocationDispatcher setLocationUpdateBackgroundMode:AGLocationBackgroundModeSignificantLocationChanges];
         [self.demoLocationDispatcher startUpdatingLocationWithBlock:^(CLLocationManager *manager, AGLocation *newLocation, AGLocation *oldLocation) {

            if(newLocation){
                self.locationView.text = [NSString stringWithFormat:@"%f;%f",newLocation.coordinate.latitude ,newLocation.coordinate.longitude];
                NSLog(@"new location ---> %@",self.locationView.text);
            }
            else{
                NSLog(@"old location ---> %@",[NSString stringWithFormat:@"%f;%f",oldLocation.coordinate.latitude ,oldLocation.coordinate.longitude]);
            }

        } errorBlock:^(CLLocationManager *manager, NSError *error) {
            [self displayDemoError:error];
        }];
```

I use this method only while the app is running in the foreground. What i was expecting is a response every 10 seconds or so, right? what i am getting is a response almost every second. It does not respect the interval at all.

**Comment by mythodeia** [comment]
basically i am trying to cover the following 2 scenarios:

1 - Have a method that will fire every x minutes and provide a location only in foreground.
2 - Have another method that will fire while the app is either in background or suspended and provide the updated location.

**Comment by kalamaznik** [comment]
Hi, mythodeia.
We've updated our library. Now you can use the following method with custom time intervals for your purposes:
- (void)updatingLocationWithBlock: (AGLocationServiceLocationUpdateBlock)block errorBlock: (AGLocationServiceLocationUpdateFailBlock) errorBlock;

Thanks for your patience.
