### ISSUE TITLE
Test using simulator?

### ISSUE THREAD

**Issue by SabatinoMasala** [agilie/AGLocationDispatcher#6]
Is there a way to test the SignificationLocationChanges using the simulator?

**Comment by kalamaznik** [comment]
Hi, SabatinoMasala!

In your simulator, goto Debug->Location->Custom and change location (input latitude and longitude ), then test it.

**Comment by SabatinoMasala** [comment]
Hi @kalamaznik,

Unfortunately using the simulator I haven't been able to trigger SignificationLocationChanges when the app is terminated.

I tried a custom GPX file, simulating a highway drive, custom coordinates, nothing seems to trigger it on my simulator.

Any more pointers?
